export const TYPE_REQUESTING = 'TYPE_REQUESTING'
export const TYPE_REQUESTED = 'TYPE_REQUESTED'
export const TYPE_REQUESTERROR = 'TYPE_REQUESTERROR'

export const PRO_LIST_REQUESTING = 'PRO_LIST_REQUESTING'
export const PRO_LIST_REQUESTED = 'PRO_LIST_REQUESTED'
export const PRO_LIST_REQUESTERROR = 'PRO_LIST_REQUESTERROR'

